# Use the official Node.js image as the base
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire application code to the container
COPY . .

# Build the React app (if required)
RUN npm run build

# Expose the port on which the React app will run
EXPOSE 3000

# Define the command to start the React app
CMD ["npm", "start"]
